site_name: Breville Dual Boiler Advanced Use
nav:
    - Home: README.md
    - Pulling Shots: PullingShots.md
    - Slayer Mod: SlayerMod.md
    - Needle Valve Upgrade: JakeValve.md
    - Upgrades: Upgrades.md
    - Replacement Part Sources: ReplacementParts.md
    - Maintenance:
      - 'OPV Adjustment': 'OPVAdjustment.md'
theme:
  name: 'material'
