site_name: Breville Dual Boiler Advanced Use
nav:
    - Home: README.md
    - Pulling Shots: PullingShots.md
    - mod:    
        - 'Slayer Mod': 'SlayerMod.md'
        - 'Needle Valve Upgrade': 'JakeValve.md'
        - 'Upgrades': 'Upgrades.md'
    - Maintenance:
      - 'OPV Adjustment': 'OPVAdjustment.md'
      - 'Replacement Parts': 'ReplacementParts.md'
theme:
  name: 'mkdocs'
  feature:
    tabs: false
